project_id = "tvmploxkzwsllvjdafmd"

[functions.cooking-agent]
verify_jwt = false

[functions.alchemy-agent]
verify_jwt = false

[functions.judge-agent]
verify_jwt = false

[functions.elevenlabs-sfx]
verify_jwt = false

[functions.generate-illustration]
verify_jwt = false